-- Tạo schema database tự động cho PRN232 LMS Lab01.
-- File này chỉ chạy khi PostgreSQL container khởi tạo volume lần đầu.

CREATE TABLE IF NOT EXISTS students (
    student_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name varchar(100) NOT NULL,
    email varchar(100) NOT NULL UNIQUE,
    date_of_birth timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS subjects (
    subject_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_code varchar(20) NOT NULL UNIQUE,
    subject_name varchar(100) NOT NULL,
    credit integer NOT NULL
);

CREATE TABLE IF NOT EXISTS semesters (
    semester_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    semester_name varchar(100) NOT NULL,
    start_date timestamp without time zone NOT NULL,
    end_date timestamp without time zone NOT NULL
);

CREATE TABLE IF NOT EXISTS courses (
    course_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name varchar(100) NOT NULL,
    semester_id integer NOT NULL,
    subject_id integer NOT NULL,
    CONSTRAINT fk_courses_semester
        FOREIGN KEY (semester_id)
        REFERENCES semesters (semester_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_courses_subject
        FOREIGN KEY (subject_id)
        REFERENCES subjects (subject_id)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS enrollments (
    enrollment_id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id integer NOT NULL,
    course_id integer NOT NULL,
    enroll_date timestamp without time zone NOT NULL,
    status varchar(20) NOT NULL,
    CONSTRAINT fk_enrollments_student
        FOREIGN KEY (student_id)
        REFERENCES students (student_id),
    CONSTRAINT fk_enrollments_course
        FOREIGN KEY (course_id)
        REFERENCES courses (course_id),
    CONSTRAINT uq_student_course UNIQUE (student_id, course_id)
);
