services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prn232-lab02-lms-api
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Host=postgres;Database=PRN232_LMS_Lab02;Username=postgres;Password=12345
      Jwt__Secret: ${JWT_SECRET:-LAB02_DOCKER_SECRET_REPLACE_WITH_ENVIRONMENT_VARIABLE_32_CHARS}
      Jwt__Issuer: PRN232.LMS.API
      Jwt__Audience: PRN232.LMS.Client
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres:17-alpine
    container_name: prn232-lab02-lms-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: PRN232_LMS_Lab02
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
    volumes:
      - prn232_lab02_lms_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d PRN232_LMS_Lab02"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"
      
  dozzle:
    image: amir20/dozzle:latest
    container_name: prn232-lab02-dozzle
    restart: unless-stopped
    ports:
      - "9999:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - api
      - postgres

volumes:
  prn232_lab02_lms_postgres_data:
